# Generated by Django 2.2.5 on 2019-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('fromEmail', models.EmailField(max_length=254)),
                ('toEmail', models.EmailField(max_length=254)),
                ('isArchived', models.BooleanField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
